import { z } from "zod"
import {
  apiSuccess,
  apiError,
  withErrorHandler,
  validateBody,
  rateLimit,
  getClientIp,
} from "@/lib/api-utils"

// ---------------------------------------------------------------------------
// POST /api/wallet/pass – request body schema
// ---------------------------------------------------------------------------

const WalletPassBodySchema = z.object({
  location: z.string().min(1, "location is required"),
  address: z.string().min(1, "address is required"),
  timeLimit: z.number().nullable().optional(),
  expiresAt: z.string().nullable().optional(),
  isProtected: z.boolean(),
  sessionId: z.string().nullable().optional(),
})

// ---------------------------------------------------------------------------
// Generate an HTML receipt for a parking session.
// This is an interim solution until real Apple/Google wallet certs are set up.
// ---------------------------------------------------------------------------

function generateReceiptHtml(data: {
  location: string
  address: string
  timeLimit: number | null | undefined
  expiresAt: string | null | undefined
  isProtected: boolean
  generatedAt: string
}): string {
  const now = new Date(data.generatedAt)
  const dateStr = now.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const timeStr = now.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  })

  let expiresStr = "No time limit"
  if (data.expiresAt) {
    const exp = new Date(data.expiresAt)
    expiresStr = exp.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    })
  } else if (data.timeLimit) {
    const exp = new Date(now.getTime() + data.timeLimit * 60_000)
    expiresStr = exp.toLocaleTimeString("en-US", {
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    })
  }

  const protectionBadge = data.isProtected
    ? `<div style="display:inline-block;padding:4px 12px;border-radius:20px;background:#e0f5e9;color:#15803d;font-size:13px;font-weight:600;">Protected</div>`
    : `<div style="display:inline-block;padding:4px 12px;border-radius:20px;background:#f5f5f5;color:#737373;font-size:13px;font-weight:600;">Standard</div>`

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Park — Parking Receipt</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f5f5;padding:24px;color:#1a1a1a}
  .receipt{max-width:380px;margin:0 auto;background:#fff;border-radius:20px;overflow:hidden;box-shadow:0 2px 16px rgba(0,0,0,.08)}
  .header{background:#1a1a1a;color:#fff;padding:28px 24px 20px}
  .logo{font-size:28px;font-weight:800;letter-spacing:-1px}
  .subtitle{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;opacity:.6;margin-top:2px}
  .body{padding:24px}
  .row{display:flex;justify-content:space-between;align-items:flex-start;padding:14px 0;border-bottom:1px solid #f0f0f0}
  .row:last-child{border-bottom:none}
  .label{font-size:12px;text-transform:uppercase;letter-spacing:.5px;color:#737373;margin-bottom:4px}
  .value{font-size:15px;font-weight:600}
  .footer{text-align:center;padding:16px 24px 24px;font-size:11px;color:#a3a3a3}
</style>
</head>
<body>
<div class="receipt">
  <div class="header">
    <div class="logo">Park</div>
    <div class="subtitle">Parking Receipt</div>
  </div>
  <div class="body">
    <div class="row">
      <div>
        <div class="label">Location</div>
        <div class="value">${escapeHtml(data.location)}</div>
        <div style="font-size:13px;color:#737373;margin-top:2px">${escapeHtml(data.address)}</div>
      </div>
    </div>
    <div class="row">
      <div>
        <div class="label">Status</div>
        <div class="value" style="color:#15803d">Can Park Here</div>
      </div>
      <div style="text-align:right">
        ${protectionBadge}
      </div>
    </div>
    <div class="row">
      <div>
        <div class="label">Parked At</div>
        <div class="value">${timeStr}</div>
        <div style="font-size:13px;color:#737373;margin-top:2px">${dateStr}</div>
      </div>
      <div style="text-align:right">
        <div class="label">Expires</div>
        <div class="value">${expiresStr}</div>
      </div>
    </div>
    ${data.timeLimit ? `<div class="row"><div><div class="label">Time Limit</div><div class="value">${data.timeLimit} min</div></div></div>` : ""}
  </div>
  <div class="footer">
    Generated by Park &middot; ${dateStr}
  </div>
</div>
</body>
</html>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

// ---------------------------------------------------------------------------
// POST /api/wallet/pass
// ---------------------------------------------------------------------------

export const POST = withErrorHandler(async (request: Request) => {
  const ip = getClientIp(request)
  const limit = rateLimit(`wallet-pass:${ip}`, 30, 60_000)
  if (!limit.allowed) {
    return apiError("Too many requests. Please try again later.", 429)
  }

  const body = await validateBody(request, WalletPassBodySchema)

  const html = generateReceiptHtml({
    location: body.location,
    address: body.address,
    timeLimit: body.timeLimit ?? null,
    expiresAt: body.expiresAt ?? null,
    isProtected: body.isProtected,
    generatedAt: new Date().toISOString(),
  })

  const base64 = Buffer.from(html, "utf-8").toString("base64")
  const url = `data:text/html;base64,${base64}`

  return apiSuccess({ url })
})
