import type { DayOfWeek } from "./types"

// ============================================================================
// INTERFACES
// ============================================================================

export interface ParkingLot {
  id: string
  name: string
  address: string
  lat: number
  lng: number
  type: "garage" | "surface" | "underground"
  operator: string
  totalSpaces: number
  ratePerHour: number
  maxDaily: number
  hours: string
  evCharging: boolean
  handicapSpaces: number
  monthlyRate: number | null
  paymentMethods: string[]
  neighborhood: string
}

export interface SignRule {
  id: string
  signText: string
  meaning: string
  status: "allowed" | "restricted" | "prohibited"
  days: DayOfWeek[]
  startTime: string
  endTime: string
  maxMinutes: number | null
  fine: number
  towRisk: boolean
}

export interface NightParkingRule {
  id: string
  neighborhood: string
  streetPattern: string
  restriction: string
  startTime: string
  endTime: string
  days: DayOfWeek[]
  fine: number
  towRisk: boolean
  permitExempt: boolean
}

export interface SpecialRule {
  id: string
  type:
    | "school-zone"
    | "hill-parking"
    | "daylighting"
    | "oversized-vehicle"
    | "commercial-zone"
    | "construction"
    | "event-day"
    | "double-parking"
    | "bike-lane"
  description: string
  fine: number
  details: string
}

export interface PermitZoneEntry {
  id: string
  zoneName: string
  neighborhood: string
  days: DayOfWeek[]
  startTime: string
  endTime: string
  nonResidentLimit: number
  annualCost: number
}

// ============================================================================
// SIGN RULES — exact text drivers see on SF streets
// ============================================================================

const signs: SignRule[] = [
  // ── TIME-LIMITED PARKING ──
  {
    id: "sign-2hr-mon-sat",
    signText: "2 HR PARKING 8AM-6PM MON THRU SAT",
    meaning: "You can park for up to 2 hours between 8 AM and 6 PM, Monday through Saturday. No limit on Sundays or after 6 PM.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "08:00",
    endTime: "18:00",
    maxMinutes: 120,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-1hr-9-6",
    signText: "1 HR PARKING 9AM-6PM MON THRU SAT",
    meaning: "You can park for up to 1 hour between 9 AM and 6 PM, Monday through Saturday. Commonly found in busy commercial corridors.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "09:00",
    endTime: "18:00",
    maxMinutes: 60,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-30min",
    signText: "30 MIN PARKING 9AM-6PM",
    meaning: "Maximum 30 minutes of parking during enforcement hours. Typically near banks, post offices, and quick-stop businesses.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "09:00",
    endTime: "18:00",
    maxMinutes: 30,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-15min-green",
    signText: "15 MIN PARKING 9AM-6PM",
    meaning: "Maximum 15 minutes. Green curb zone for very quick stops only.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "09:00",
    endTime: "18:00",
    maxMinutes: 15,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-4hr",
    signText: "4 HR PARKING 8AM-6PM MON THRU FRI",
    meaning: "You can park for up to 4 hours between 8 AM and 6 PM on weekdays. No limit evenings, weekends.",
    status: "restricted",
    days: [1, 2, 3, 4, 5],
    startTime: "08:00",
    endTime: "18:00",
    maxMinutes: 240,
    fine: 76,
    towRisk: false,
  },

  // ── STREET CLEANING ──
  {
    id: "sign-sweep-mon-8-10",
    signText: "NO PARKING STREET CLEANING MON 8AM-10AM",
    meaning: "Your car will be ticketed ($76) if parked here during Monday street sweeping. Move your car before 8 AM Monday.",
    status: "prohibited",
    days: [1],
    startTime: "08:00",
    endTime: "10:00",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-sweep-tue-8-10",
    signText: "NO PARKING STREET CLEANING TUE 8AM-10AM",
    meaning: "No parking during Tuesday street sweeping from 8 to 10 AM. Move your car before 8 AM Tuesday.",
    status: "prohibited",
    days: [2],
    startTime: "08:00",
    endTime: "10:00",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-sweep-wed-10-12",
    signText: "NO PARKING STREET CLEANING WED 10AM-12PM",
    meaning: "No parking during Wednesday street sweeping from 10 AM to noon.",
    status: "prohibited",
    days: [3],
    startTime: "10:00",
    endTime: "12:00",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-sweep-thu-8-10",
    signText: "NO PARKING STREET CLEANING THU 8AM-10AM",
    meaning: "No parking during Thursday street sweeping from 8 to 10 AM.",
    status: "prohibited",
    days: [4],
    startTime: "08:00",
    endTime: "10:00",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-sweep-fri-8-10",
    signText: "NO PARKING STREET CLEANING FRI 8AM-10AM",
    meaning: "No parking during Friday street sweeping from 8 to 10 AM.",
    status: "prohibited",
    days: [5],
    startTime: "08:00",
    endTime: "10:00",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },

  // ── TOW-AWAY ZONES ──
  {
    id: "sign-tow-7-9-am",
    signText: "TOW AWAY NO STOPPING 7-9AM MON-FRI",
    meaning: "Absolutely no stopping or parking 7-9 AM weekdays. Your car WILL be towed. This is a rush-hour traffic lane. Tow + storage fees total $500+.",
    status: "prohibited",
    days: [1, 2, 3, 4, 5],
    startTime: "07:00",
    endTime: "09:00",
    maxMinutes: null,
    fine: 500,
    towRisk: true,
  },
  {
    id: "sign-tow-3-7-pm",
    signText: "TOW AWAY NO STOPPING 3-7PM MON-FRI",
    meaning: "Absolutely no stopping or parking 3-7 PM weekdays. Rush-hour tow-away lane. Your car WILL be towed. Expect $500+ total cost.",
    status: "prohibited",
    days: [1, 2, 3, 4, 5],
    startTime: "15:00",
    endTime: "19:00",
    maxMinutes: null,
    fine: 500,
    towRisk: true,
  },
  {
    id: "sign-tow-4-6-pm",
    signText: "TOW AWAY NO STOPPING 4-6PM MON-FRI",
    meaning: "No stopping or parking 4-6 PM weekdays. Rush-hour tow-away zone.",
    status: "prohibited",
    days: [1, 2, 3, 4, 5],
    startTime: "16:00",
    endTime: "18:00",
    maxMinutes: null,
    fine: 500,
    towRisk: true,
  },
  {
    id: "sign-tow-anytime",
    signText: "TOW AWAY NO PARKING ANYTIME",
    meaning: "No parking at any time, any day. You will be towed. Often near fire stations, hospitals, and emergency zones.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 500,
    towRisk: true,
  },

  // ── RESIDENTIAL PERMIT PARKING ──
  {
    id: "sign-rpp-2hr",
    signText: "RESIDENTIAL PERMIT PARKING ONLY 2HR LIMIT 8AM-6PM MON-FRI AREA [X]",
    meaning: "Non-residents may park for 2 hours max during enforcement. Residents with the area permit are exempt from the time limit.",
    status: "restricted",
    days: [1, 2, 3, 4, 5],
    startTime: "08:00",
    endTime: "18:00",
    maxMinutes: 120,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-rpp-1hr",
    signText: "RESIDENTIAL PERMIT PARKING ONLY 1HR LIMIT 8AM-10PM EVERY DAY AREA [X]",
    meaning: "Non-residents may park for 1 hour max. Enforced 8 AM to 10 PM every day including weekends. High-demand residential zone.",
    status: "restricted",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "08:00",
    endTime: "22:00",
    maxMinutes: 60,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-rpp-permit-only",
    signText: "NO PARKING EXCEPT VEHICLES WITH AREA [X] PERMIT",
    meaning: "Only vehicles displaying the specified area permit can park here. All others will be cited. Common in heavily impacted residential blocks.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },

  // ── NO PARKING / NO STOPPING ──
  {
    id: "sign-no-parking-anytime",
    signText: "NO PARKING ANYTIME",
    meaning: "No parking at any time, any day. Standing briefly to load/unload passengers is usually OK, but you cannot leave the vehicle.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
  {
    id: "sign-no-stopping-anytime",
    signText: "NO STOPPING ANYTIME",
    meaning: "You cannot stop your vehicle here for any reason, not even to drop off passengers. Strictly enforced.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },

  // ── COMMERCIAL / LOADING ZONES ──
  {
    id: "sign-commercial-loading",
    signText: "COMMERCIAL LOADING ZONE 7AM-6PM MON-SAT",
    meaning: "Only commercial vehicles actively loading/unloading goods may stop here during the posted hours. Yellow curb zone. 30-minute limit.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "07:00",
    endTime: "18:00",
    maxMinutes: 30,
    fine: 110,
    towRisk: false,
  },
  {
    id: "sign-passenger-loading",
    signText: "PASSENGER LOADING ZONE 7AM-6PM",
    meaning: "White curb zone. For picking up or dropping off passengers only. Driver must remain with vehicle. 5-minute maximum.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "07:00",
    endTime: "18:00",
    maxMinutes: 5,
    fine: 110,
    towRisk: false,
  },
  {
    id: "sign-truck-loading",
    signText: "TRUCK LOADING ONLY 7AM-6PM MON-FRI",
    meaning: "Reserved for trucks actively loading/unloading. Passenger vehicles cannot park here during enforcement hours even briefly.",
    status: "prohibited",
    days: [1, 2, 3, 4, 5],
    startTime: "07:00",
    endTime: "18:00",
    maxMinutes: 30,
    fine: 110,
    towRisk: false,
  },

  // ── BUS / TRANSIT ──
  {
    id: "sign-bus-zone",
    signText: "BUS ZONE NO PARKING",
    meaning: "Reserved for Muni/transit buses. No stopping or parking at any time. Vehicles will be towed.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 283,
    towRisk: true,
  },
  {
    id: "sign-transit-only",
    signText: "TRANSIT ONLY LANE TOW-AWAY",
    meaning: "Lane reserved for Muni buses and taxis only. No private vehicles. Violators towed.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 283,
    towRisk: true,
  },

  // ── DISABLED / HANDICAP ──
  {
    id: "sign-disabled-parking",
    signText: "DISABLED PARKING ONLY SPECIAL PLATE OR PLACARD REQUIRED",
    meaning: "Reserved for vehicles displaying a valid disabled placard or plate. Blue curb zone. Violators face heavy fines ($250-$1000).",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 250,
    towRisk: true,
  },

  // ── METERED PARKING ──
  {
    id: "sign-metered-2hr",
    signText: "2 HR METERED PARKING 9AM-6PM MON-SAT",
    meaning: "Pay the meter for up to 2 hours. Meters enforced 9 AM - 6 PM Monday through Saturday. Free on Sundays and after 6 PM.",
    status: "restricted",
    days: [1, 2, 3, 4, 5, 6],
    startTime: "09:00",
    endTime: "18:00",
    maxMinutes: 120,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-metered-extended",
    signText: "METERED PARKING 9AM-10PM EVERY DAY",
    meaning: "Pay the meter until 10 PM every day including Sundays. Common in tourist areas like Fisherman's Wharf. Higher rates apply.",
    status: "restricted",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "09:00",
    endTime: "22:00",
    maxMinutes: 120,
    fine: 76,
    towRisk: false,
  },

  // ── MISCELLANEOUS ──
  {
    id: "sign-temp-no-parking",
    signText: "TEMPORARY NO PARKING [DATE] [TIME]",
    meaning: "Temporary no parking for construction, filming, moving, or events. Check the posted dates and times. Vehicles will be towed if present during the restricted period.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
  {
    id: "sign-motorcycle-only",
    signText: "MOTORCYCLE PARKING ONLY",
    meaning: "Reserved for motorcycles and scooters only. Cars parked here will be cited.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-ev-charging",
    signText: "ELECTRIC VEHICLE CHARGING ONLY 4HR LIMIT",
    meaning: "Reserved for electric vehicles actively charging. You must be plugged in. 4-hour maximum. Non-EV or non-charging vehicles will be cited.",
    status: "restricted",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: 240,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-carshare",
    signText: "CAR SHARE VEHICLE ONLY",
    meaning: "Reserved for designated car-share vehicles (Zipcar, Getaround, etc.) at all times. Private vehicles will be cited and towed.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
  {
    id: "sign-curb-wheels",
    signText: "CURB WHEELS PARK IN GEAR SET BRAKE",
    meaning: "You are on a steep hill. By law you MUST curb your wheels. Uphill: turn wheels away from curb. Downhill: turn wheels toward curb. $76 fine if you don't.",
    status: "restricted",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 76,
    towRisk: false,
  },
  {
    id: "sign-snow-emergency",
    signText: "SNOW EMERGENCY ROUTE NO PARKING DURING SNOW EMERGENCY",
    meaning: "Rare in SF, but found on some elevated roads. No parking when a snow emergency is declared.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
  {
    id: "sign-consulate-zone",
    signText: "NO PARKING CONSULATE ZONE",
    meaning: "Reserved zone near foreign consulate. No parking at any time. Strictly enforced by SFMTA and federal agencies.",
    status: "prohibited",
    days: [0, 1, 2, 3, 4, 5, 6],
    startTime: "00:00",
    endTime: "23:59",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
  {
    id: "sign-permitted-construction",
    signText: "NO PARKING CONSTRUCTION ZONE PERMIT #[XXXX]",
    meaning: "Active construction zone with a valid SFMTA permit. No parking during posted hours. Vehicles towed at owner's expense.",
    status: "prohibited",
    days: [1, 2, 3, 4, 5],
    startTime: "07:00",
    endTime: "17:00",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
  {
    id: "sign-farmers-market",
    signText: "NO PARKING [DAY] 6AM-2PM FARMERS MARKET",
    meaning: "Temporary weekly closure for farmers market. Common at Ferry Building (Sat), Alemany (Sat), and other neighborhood markets.",
    status: "prohibited",
    days: [6],
    startTime: "06:00",
    endTime: "14:00",
    maxMinutes: null,
    fine: 110,
    towRisk: true,
  },
]

// ============================================================================
// NIGHT PARKING RULES — by neighborhood
// ============================================================================

const nightParking: NightParkingRule[] = [
  {
    id: "night-sf-citywide-72hr",
    neighborhood: "Citywide",
    streetPattern: "*",
    restriction: "72-hour limit: no vehicle may park in any one spot on a public street for more than 72 consecutive hours. Enforced by complaint.",
    startTime: "00:00",
    endTime: "23:59",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: true,
    permitExempt: false,
  },
  {
    id: "night-mission",
    neighborhood: "Mission",
    streetPattern: "valencia st|mission st|guerrero st|folsom st|16th-26th",
    restriction: "No overnight restrictions beyond the 72-hour rule, but RPP Zone N enforced 8AM-6PM. Frequent overnight break-ins -- avoid leaving valuables visible.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-soma",
    neighborhood: "SOMA",
    streetPattern: "howard st|folsom st|harrison st|bryant st|brannan st",
    restriction: "No special overnight ban, but many blocks have tow-away starting at 7 AM for rush hour. Move before 7 AM on weekdays.",
    startTime: "00:00",
    endTime: "07:00",
    days: [1, 2, 3, 4, 5],
    fine: 500,
    towRisk: true,
    permitExempt: false,
  },
  {
    id: "night-financial",
    neighborhood: "Financial District",
    streetPattern: "market st|montgomery st|kearny st|pine st|bush st|sansome st",
    restriction: "Many streets convert to tow-away at 7 AM. Overnight parking is legal but you must move by 7 AM on weekdays for rush-hour lanes.",
    startTime: "00:00",
    endTime: "07:00",
    days: [1, 2, 3, 4, 5],
    fine: 500,
    towRisk: true,
    permitExempt: false,
  },
  {
    id: "night-marina",
    neighborhood: "Marina",
    streetPattern: "chestnut st|lombard st|fillmore st|scott st|divisadero st",
    restriction: "RPP Zone M enforced. No dedicated overnight ban. Abundant overnight parking on residential side streets. Beach/Marina Blvd has 4-hour limits.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-castro",
    neighborhood: "Castro",
    streetPattern: "castro st|market st|18th st|noe st|collingwood st",
    restriction: "RPP Zone L enforced during day. Night parking generally unrestricted on residential blocks. Bar areas busy late on weekends.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-haight",
    neighborhood: "Haight-Ashbury",
    streetPattern: "haight st|ashbury st|masonic ave|cole st|clayton st",
    restriction: "RPP Zone P enforced. No overnight ban. High break-in area after midnight -- park in well-lit spots.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-north-beach",
    neighborhood: "North Beach",
    streetPattern: "columbus ave|grant ave|broadway|vallejo st|green st",
    restriction: "RPP Zone F enforced. Heavy nightlife traffic on Broadway Thu-Sat. No dedicated overnight ban but some blocks have posted no-parking 2-6AM for cleaning.",
    startTime: "02:00",
    endTime: "06:00",
    days: [5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-richmond",
    neighborhood: "Richmond",
    streetPattern: "clement st|geary blvd|balboa st|fulton st|cabrillo st",
    restriction: "Very few overnight restrictions. The avenues have ample parking. 72-hour rule applies. No RPP in most of outer Richmond.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-sunset",
    neighborhood: "Sunset",
    streetPattern: "irving st|judah st|noriega st|taraval st|lincoln way",
    restriction: "Generally unrestricted overnight. Ample street parking throughout. No RPP in most of Sunset. 72-hour rule applies.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-hayes-valley",
    neighborhood: "Hayes Valley",
    streetPattern: "hayes st|octavia st|fell st|oak st|grove st|ivy st",
    restriction: "RPP Zone V enforced. Fell and Oak are major tow-away streets starting at 7 AM weekdays. Move vehicles from Fell/Oak by 7 AM.",
    startTime: "00:00",
    endTime: "07:00",
    days: [1, 2, 3, 4, 5],
    fine: 500,
    towRisk: true,
    permitExempt: false,
  },
  {
    id: "night-tenderloin",
    neighborhood: "Tenderloin",
    streetPattern: "turk st|eddy st|ellis st|o'farrell st|leavenworth st|jones st",
    restriction: "Frequent overnight enforcement. Some blocks have scheduled cleaning as early as 6 AM. High vehicle break-in area. Use garages if possible.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-nob-hill",
    neighborhood: "Nob Hill",
    streetPattern: "california st|jones st|leavenworth st|powell st|mason st",
    restriction: "RPP Zone D enforced. Steep hills -- must curb wheels at all times. Overnight parking legal on most blocks. California St near hotels has metered zones.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-potrero-hill",
    neighborhood: "Potrero Hill",
    streetPattern: "potrero ave|18th st|20th st|wisconsin st|connecticut st",
    restriction: "Mostly unrestricted overnight. RPP Zone R on some blocks. Ample parking in residential areas. Mind steep-grade wheel-curbing requirements.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-bernal-heights",
    neighborhood: "Bernal Heights",
    streetPattern: "cortland ave|folsom st|mission st|cesar chavez",
    restriction: "Very few overnight restrictions. Residential neighborhood with ample parking. 72-hour rule applies. Some RPP on blocks near Mission corridor.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-dogpatch",
    neighborhood: "Dogpatch",
    streetPattern: "3rd st|illinois st|tennessee st|20th st|22nd st",
    restriction: "Few overnight restrictions. Industrial-zoned blocks may have commercial vehicle zones starting at 7 AM. Growing RPP coverage.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-pacific-heights",
    neighborhood: "Pacific Heights",
    streetPattern: "fillmore st|divisadero st|jackson st|washington st|broadway",
    restriction: "RPP Zone B enforced during day. Overnight parking generally unrestricted on residential blocks. Very steep streets -- always curb wheels.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: true,
  },
  {
    id: "night-excelsior",
    neighborhood: "Excelsior",
    streetPattern: "mission st|geneva ave|excelsior ave|brazil ave",
    restriction: "Mostly unrestricted overnight. Residential neighborhood. No RPP in most of Excelsior. 72-hour rule applies.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-bayview",
    neighborhood: "Bayview-Hunters Point",
    streetPattern: "3rd st|evans ave|innes ave|jennings st",
    restriction: "Few overnight restrictions. 3rd St corridor is swept weekly. Some industrial blocks have commercial-only parking. 72-hour rule applies.",
    startTime: "00:00",
    endTime: "06:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 76,
    towRisk: false,
    permitExempt: false,
  },
  {
    id: "night-fishermans-wharf",
    neighborhood: "Fisherman's Wharf",
    streetPattern: "jefferson st|taylor st|beach st|north point st|mason st",
    restriction: "Meters enforced until 10 PM every day. After 10 PM, overnight parking is free at meters until 9 AM. Popular overnight spot but high break-in risk.",
    startTime: "22:00",
    endTime: "09:00",
    days: [0, 1, 2, 3, 4, 5, 6],
    fine: 0,
    towRisk: false,
    permitExempt: false,
  },
]

// ============================================================================
// PARKING LOTS & GARAGES — real addresses, coordinates, and rates
// ============================================================================

const parkingLots: ParkingLot[] = [
  // ── SFMTA-OPERATED GARAGES ──
  {
    id: "lot-sutter-stockton",
    name: "Sutter Stockton Garage",
    address: "444 Stockton St, San Francisco, CA 94108",
    lat: 37.78899,
    lng: -122.40674,
    type: "garage",
    operator: "SFMTA",
    totalSpaces: 1865,
    ratePerHour: 4.00,
    maxDaily: 36,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 36,
    monthlyRate: 350,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Union Square",
  },
  {
    id: "lot-union-square",
    name: "Union Square Garage",
    address: "333 Post St, San Francisco, CA 94108",
    lat: 37.78779,
    lng: -122.40722,
    type: "underground",
    operator: "SFMTA",
    totalSpaces: 985,
    ratePerHour: 4.00,
    maxDaily: 36,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 20,
    monthlyRate: 350,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Union Square",
  },
  {
    id: "lot-civic-center",
    name: "Civic Center Garage",
    address: "355 McAllister St, San Francisco, CA 94102",
    lat: 37.78058,
    lng: -122.41713,
    type: "underground",
    operator: "SFMTA",
    totalSpaces: 840,
    ratePerHour: 4.00,
    maxDaily: 30,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 18,
    monthlyRate: 300,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Civic Center",
  },
  {
    id: "lot-fifth-mission",
    name: "Fifth & Mission Garage",
    address: "833 Mission St, San Francisco, CA 94103",
    lat: 37.78268,
    lng: -122.40527,
    type: "garage",
    operator: "SFMTA",
    totalSpaces: 2585,
    ratePerHour: 4.00,
    maxDaily: 36,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 52,
    monthlyRate: 325,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "SOMA",
  },
  {
    id: "lot-moscone",
    name: "Moscone Center Garage",
    address: "255 3rd St, San Francisco, CA 94103",
    lat: 37.78447,
    lng: -122.40100,
    type: "underground",
    operator: "SFMTA",
    totalSpaces: 732,
    ratePerHour: 4.00,
    maxDaily: 36,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 16,
    monthlyRate: 325,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "SOMA",
  },
  {
    id: "lot-st-marys",
    name: "St. Mary's Square Garage",
    address: "433 Kearny St, San Francisco, CA 94108",
    lat: 37.79165,
    lng: -122.40459,
    type: "underground",
    operator: "SFMTA",
    totalSpaces: 414,
    ratePerHour: 4.00,
    maxDaily: 30,
    hours: "6AM-12AM",
    evCharging: false,
    handicapSpaces: 8,
    monthlyRate: 300,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Chinatown",
  },
  {
    id: "lot-portsmouth",
    name: "Portsmouth Square Garage",
    address: "733 Kearny St, San Francisco, CA 94108",
    lat: 37.79494,
    lng: -122.40531,
    type: "underground",
    operator: "SFMTA",
    totalSpaces: 468,
    ratePerHour: 3.50,
    maxDaily: 28,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 10,
    monthlyRate: 275,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Chinatown",
  },
  {
    id: "lot-north-beach",
    name: "North Beach Garage",
    address: "735 Vallejo St, San Francisco, CA 94133",
    lat: 37.79845,
    lng: -122.40864,
    type: "garage",
    operator: "SFMTA",
    totalSpaces: 203,
    ratePerHour: 3.50,
    maxDaily: 28,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 6,
    monthlyRate: 275,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "North Beach",
  },
  {
    id: "lot-lombard-street",
    name: "Lombard Street Garage",
    address: "2055 Lombard St, San Francisco, CA 94123",
    lat: 37.79959,
    lng: -122.43572,
    type: "garage",
    operator: "SFMTA",
    totalSpaces: 204,
    ratePerHour: 3.00,
    maxDaily: 24,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 6,
    monthlyRate: 250,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Marina",
  },
  {
    id: "lot-golden-gateway",
    name: "Golden Gateway Garage",
    address: "250 Clay St, San Francisco, CA 94111",
    lat: 37.79564,
    lng: -122.39974,
    type: "underground",
    operator: "SFMTA",
    totalSpaces: 1054,
    ratePerHour: 4.00,
    maxDaily: 36,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 22,
    monthlyRate: 350,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Financial District",
  },
  {
    id: "lot-performing-arts",
    name: "Performing Arts Garage",
    address: "360 Grove St, San Francisco, CA 94102",
    lat: 37.77818,
    lng: -122.42101,
    type: "garage",
    operator: "SFMTA",
    totalSpaces: 598,
    ratePerHour: 4.00,
    maxDaily: 30,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 12,
    monthlyRate: 300,
    paymentMethods: ["credit", "debit", "cash", "PayByPhone"],
    neighborhood: "Civic Center",
  },

  // ── PRIVATE / OTHER GARAGES ──
  {
    id: "lot-stockton-wharf",
    name: "Pier 39 Garage",
    address: "2550 Powell St, San Francisco, CA 94133",
    lat: 37.80877,
    lng: -122.40986,
    type: "garage",
    operator: "Pier 39 LP",
    totalSpaces: 1500,
    ratePerHour: 8.00,
    maxDaily: 50,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 30,
    monthlyRate: null,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Fisherman's Wharf",
  },
  {
    id: "lot-ghirardelli",
    name: "Ghirardelli Square Garage",
    address: "900 North Point St, San Francisco, CA 94109",
    lat: 37.80576,
    lng: -122.42264,
    type: "garage",
    operator: "Jamestown LP",
    totalSpaces: 170,
    ratePerHour: 7.00,
    maxDaily: 45,
    hours: "7AM-11PM",
    evCharging: false,
    handicapSpaces: 4,
    monthlyRate: null,
    paymentMethods: ["credit", "debit"],
    neighborhood: "Fisherman's Wharf",
  },
  {
    id: "lot-embarcadero-center",
    name: "Embarcadero Center Garage",
    address: "150 Drumm St, San Francisco, CA 94111",
    lat: 37.79393,
    lng: -122.39668,
    type: "underground",
    operator: "Boston Properties",
    totalSpaces: 2100,
    ratePerHour: 6.00,
    maxDaily: 42,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 42,
    monthlyRate: 425,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Financial District",
  },
  {
    id: "lot-mission-bartlett",
    name: "Mission Bartlett Garage",
    address: "3255 21st St, San Francisco, CA 94110",
    lat: 37.75727,
    lng: -122.41862,
    type: "garage",
    operator: "Impark",
    totalSpaces: 288,
    ratePerHour: 2.50,
    maxDaily: 18,
    hours: "6AM-12AM",
    evCharging: false,
    handicapSpaces: 8,
    monthlyRate: 200,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Mission",
  },
  {
    id: "lot-16th-hoff",
    name: "16th & Hoff Street Garage",
    address: "42 Hoff St, San Francisco, CA 94110",
    lat: 37.76491,
    lng: -122.42214,
    type: "garage",
    operator: "LAZ Parking",
    totalSpaces: 227,
    ratePerHour: 3.00,
    maxDaily: 20,
    hours: "7AM-11PM",
    evCharging: false,
    handicapSpaces: 6,
    monthlyRate: 225,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Mission",
  },
  {
    id: "lot-japan-center",
    name: "Japan Center Garage",
    address: "1610 Geary Blvd, San Francisco, CA 94115",
    lat: 37.78530,
    lng: -122.43133,
    type: "garage",
    operator: "Ace Parking",
    totalSpaces: 543,
    ratePerHour: 3.00,
    maxDaily: 25,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 12,
    monthlyRate: 250,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Japantown",
  },
  {
    id: "lot-opera-plaza",
    name: "Opera Plaza Garage",
    address: "601 Van Ness Ave, San Francisco, CA 94102",
    lat: 37.78014,
    lng: -122.42120,
    type: "garage",
    operator: "Imperial Parking",
    totalSpaces: 305,
    ratePerHour: 4.00,
    maxDaily: 30,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 8,
    monthlyRate: 300,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Civic Center",
  },
  {
    id: "lot-market-square",
    name: "Market Square Garage",
    address: "1355 Market St, San Francisco, CA 94103",
    lat: 37.77589,
    lng: -122.41511,
    type: "underground",
    operator: "ABM Parking",
    totalSpaces: 640,
    ratePerHour: 5.00,
    maxDaily: 35,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 14,
    monthlyRate: 375,
    paymentMethods: ["credit", "debit"],
    neighborhood: "Mid-Market",
  },
  {
    id: "lot-kezar-stadium",
    name: "Kezar Stadium Parking Lot",
    address: "755 Stanyan St, San Francisco, CA 94117",
    lat: 37.76668,
    lng: -122.45411,
    type: "surface",
    operator: "SF Recreation & Parks",
    totalSpaces: 200,
    ratePerHour: 0,
    maxDaily: 0,
    hours: "6AM-10PM",
    evCharging: false,
    handicapSpaces: 8,
    monthlyRate: null,
    paymentMethods: [],
    neighborhood: "Haight-Ashbury",
  },
  {
    id: "lot-music-concourse",
    name: "Music Concourse Garage",
    address: "55 Music Concourse Dr, San Francisco, CA 94118",
    lat: 37.77063,
    lng: -122.46722,
    type: "underground",
    operator: "City of SF / ABM",
    totalSpaces: 800,
    ratePerHour: 5.00,
    maxDaily: 32,
    hours: "7AM-10PM",
    evCharging: true,
    handicapSpaces: 16,
    monthlyRate: null,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "Golden Gate Park",
  },
  {
    id: "lot-westfield-centre",
    name: "Westfield Centre Garage",
    address: "845 Market St, San Francisco, CA 94103",
    lat: 37.78497,
    lng: -122.40620,
    type: "garage",
    operator: "Westfield / ABM",
    totalSpaces: 375,
    ratePerHour: 5.00,
    maxDaily: 40,
    hours: "6AM-12AM",
    evCharging: true,
    handicapSpaces: 10,
    monthlyRate: 375,
    paymentMethods: ["credit", "debit"],
    neighborhood: "SOMA",
  },
  {
    id: "lot-metreon",
    name: "Metreon / Yerba Buena Garage",
    address: "175 4th St, San Francisco, CA 94103",
    lat: 37.78372,
    lng: -122.40367,
    type: "garage",
    operator: "ABM Parking",
    totalSpaces: 740,
    ratePerHour: 5.00,
    maxDaily: 40,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 15,
    monthlyRate: 350,
    paymentMethods: ["credit", "debit", "cash"],
    neighborhood: "SOMA",
  },
  {
    id: "lot-noe-valley",
    name: "Noe Valley Town Square Lot",
    address: "3861 24th St, San Francisco, CA 94114",
    lat: 37.75089,
    lng: -122.43274,
    type: "surface",
    operator: "City of SF",
    totalSpaces: 40,
    ratePerHour: 0,
    maxDaily: 0,
    hours: "24/7",
    evCharging: false,
    handicapSpaces: 2,
    monthlyRate: null,
    paymentMethods: [],
    neighborhood: "Noe Valley",
  },
  {
    id: "lot-caltrain-4th-king",
    name: "Caltrain 4th & King Surface Lot",
    address: "600 4th St, San Francisco, CA 94107",
    lat: 37.77571,
    lng: -122.39503,
    type: "surface",
    operator: "SFMTA / Caltrain",
    totalSpaces: 40,
    ratePerHour: 3.00,
    maxDaily: 15,
    hours: "6AM-10PM",
    evCharging: false,
    handicapSpaces: 4,
    monthlyRate: null,
    paymentMethods: ["credit", "debit", "PayByPhone"],
    neighborhood: "Mission Bay",
  },
  {
    id: "lot-ucsf-mission-bay",
    name: "UCSF Mission Bay Parking Garage",
    address: "1625 Owens St, San Francisco, CA 94158",
    lat: 37.76782,
    lng: -122.39268,
    type: "garage",
    operator: "UCSF",
    totalSpaces: 1200,
    ratePerHour: 5.00,
    maxDaily: 30,
    hours: "24/7",
    evCharging: true,
    handicapSpaces: 24,
    monthlyRate: 280,
    paymentMethods: ["credit", "debit"],
    neighborhood: "Mission Bay",
  },
  {
    id: "lot-stonestown",
    name: "Stonestown Galleria Parking",
    address: "3251 20th Ave, San Francisco, CA 94132",
    lat: 37.72868,
    lng: -122.47530,
    type: "surface",
    operator: "Brookfield Properties",
    totalSpaces: 2200,
    ratePerHour: 0,
    maxDaily: 0,
    hours: "6AM-10PM",
    evCharging: true,
    handicapSpaces: 40,
    monthlyRate: null,
    paymentMethods: [],
    neighborhood: "Stonestown",
  },
]

// ============================================================================
// SPECIAL RULES — unique SF parking rules people forget about
// ============================================================================

const specialRules: SpecialRule[] = [
  {
    id: "special-hill-parking",
    type: "hill-parking",
    description: "Curb your wheels on any grade over 3%",
    fine: 76,
    details:
      "San Francisco is one of the few cities that actively enforces hill-parking laws. On ANY grade exceeding 3%, you must: UPHILL (with curb) = turn front wheels AWAY from curb; DOWNHILL = turn front wheels TOWARD curb; UPHILL (no curb) = turn wheels toward the road edge. Always set parking brake and leave in gear (manual) or Park (auto). SFMTA parking control officers carry inclinometers.",
  },
  {
    id: "special-daylighting-ab413",
    type: "daylighting",
    description: "AB 413 daylighting law: no parking within 20 feet of any intersection crosswalk",
    fine: 76,
    details:
      "California AB 413 (effective January 2025) prohibits parking or stopping within 20 feet of any marked or unmarked crosswalk at an intersection. This replaces the old 15-foot rule. Purpose: improves visibility of pedestrians for turning drivers. Red curb paint is NOT required -- the law applies even at unpainted curbs. SFMTA can cite you even without paint. Applies citywide at every intersection.",
  },
  {
    id: "special-hydrant-15ft",
    type: "daylighting",
    description: "No parking within 15 feet of a fire hydrant",
    fine: 110,
    details:
      "California Vehicle Code 22514: No stopping or parking within 15 feet of a fire hydrant. In practice, SFFD will break your windows and run a hose through your car during a fire. Fine is $110 minimum. Red curb paint around hydrants is common but not required for enforcement.",
  },
  {
    id: "special-double-parking",
    type: "double-parking",
    description: "Double parking is always illegal",
    fine: 110,
    details:
      "Double parking (stopping in a travel lane beside a parked car) is illegal at all times, even with hazard lights on. Fine is $110. If you block traffic or a bicycle lane, fines increase. Commercial vehicles get no exception in SF. SFMTA PCOs and DPT aggressively cite double parking, especially on Valencia, Mission, Geary, and Fillmore streets.",
  },
  {
    id: "special-bike-lane",
    type: "bike-lane",
    description: "No stopping, standing, or parking in a bike lane",
    fine: 110,
    details:
      "Parking, stopping, or standing in a designated bicycle lane is prohibited at all times. Fine is $110. This includes green-painted bike lanes, buffered bike lanes, and marked bike lanes. Even brief stops for loading/unloading are not permitted. Heavily enforced on the Wiggle route, Valencia St, Market St, 2nd St, Polk St, and the Embarcadero.",
  },
  {
    id: "special-oversized-rv",
    type: "oversized-vehicle",
    description: "Oversized vehicles (over 22 feet or 7 feet high) restricted on many streets",
    fine: 110,
    details:
      "Vehicles exceeding 22 feet in length or 7 feet in height (including RVs, campers, and large trucks) are subject to additional restrictions. Certain streets and neighborhoods prohibit oversized vehicle parking entirely. The 72-hour rule is strictly enforced against RVs. SFMTA may tow oversized vehicles parked on residential streets if complaints are filed. Some streets near Golden Gate Park and the Great Highway have posted oversized vehicle bans.",
  },
  {
    id: "special-school-zone-1",
    type: "school-zone",
    description: "No parking in school loading zones during school hours",
    fine: 110,
    details:
      "White and yellow curb zones near schools are strictly enforced 7-8:30 AM and 2-3:30 PM on school days. Fines are $110. Some schools have additional posted hours. No stopping, standing, or parking in the school zone. Double fines may apply. School zones also have reduced speed limits (15-25 mph). SFPD frequently patrols school zones.",
  },
  {
    id: "special-school-zone-2",
    type: "school-zone",
    description: "School bus red-light stop: must stop when school bus red lights are flashing",
    fine: 695,
    details:
      "When a school bus has its red lights flashing and stop sign extended, all vehicles in BOTH directions must stop. Fine is $695 for the first offense in California. This applies on all streets unless separated by a physical median. SF has red-light cameras on some school buses.",
  },
  {
    id: "special-commercial-zone",
    type: "commercial-zone",
    description: "Yellow curb commercial loading zones enforce 30-minute limits for commercial vehicles",
    fine: 110,
    details:
      "Yellow curb zones are for commercial vehicles actively loading/unloading goods only, typically 7 AM - 6 PM Monday-Saturday. Maximum 30 minutes. After posted hours, yellow zones become general parking. Non-commercial vehicles will be cited during enforcement. Driver must remain in the vicinity. Common on Market, Mission, Valencia, Clement, Columbus, and downtown streets.",
  },
  {
    id: "special-construction-permit",
    type: "construction",
    description: "Temporary construction no-parking zones require 72-hour posted notice",
    fine: 110,
    details:
      "SFMTA issues permits for temporary no-parking zones for construction, moving, filming, and special events. The permit holder must post the no-parking signs at least 72 hours before the restriction begins. Signs must include the SFMTA permit number, dates, and times. Vehicles present during the restriction will be towed at owner's expense. If signs were posted less than 72 hours before, you can contest the ticket.",
  },
  {
    id: "special-event-giants",
    type: "event-day",
    description: "Giants game day parking restrictions around Oracle Park",
    fine: 110,
    details:
      "On SF Giants game days, special event parking restrictions are enforced in the Mission Bay, SOMA, and South Beach neighborhoods surrounding Oracle Park (24 Willie Mays Plaza). Many streets become tow-away zones 2 hours before game time. Residential permit holders in Zone R are exempt on some blocks. Street meters around the ballpark may have extended hours. Signs are posted as 'EVENT DAY NO PARKING.'",
  },
  {
    id: "special-event-chase",
    type: "event-day",
    description: "Warriors/Chase Center event day restrictions in Mission Bay",
    fine: 110,
    details:
      "On Warriors game days and major events at Chase Center (1 Warriors Way), temporary no-parking zones are activated on 3rd St, Terry Francois Blvd, and surrounding streets. Restrictions typically begin 3 hours before events. Vehicles will be towed. Use the Chase Center Garage or public transit (T-Third Muni). Signs posted as 'EVENT DAY TOW AWAY.'",
  },
  {
    id: "special-event-candlestick",
    type: "event-day",
    description: "Special event restrictions for large venue events at various locations",
    fine: 110,
    details:
      "Large-scale events at Golden Gate Park (Outside Lands, Hardly Strictly), Bill Graham Civic Auditorium, Moscone Center, and other venues trigger temporary no-parking zones. Check SFMTA.com for event-day restrictions. Signs are posted 72 hours before. Neighborhoods most affected: Richmond (for GGP events), Civic Center (for concerts/conventions), SOMA (for Moscone events).",
  },
  {
    id: "special-driveway-blocking",
    type: "double-parking",
    description: "Blocking any driveway entrance or exit is illegal",
    fine: 110,
    details:
      "You may not park in front of any public or private driveway, even partially. This includes driveways that appear unused. The property owner can request an immediate tow. Fine is $110, plus tow fees if applicable. SFMTA can cite you even without a complaint. This applies 24/7. Garage entrances, loading docks, and curb cuts for accessibility also count.",
  },
  {
    id: "special-sidewalk-parking",
    type: "double-parking",
    description: "Parking on the sidewalk is always illegal",
    fine: 165,
    details:
      "No part of your vehicle may extend onto the sidewalk. This includes having your rear bumper overhang the curb. Fine is $165. SF has many narrow streets where this is tempting but always illegal. Motorcycles also may not park on sidewalks. The only exception is explicitly designated motorcycle parking areas.",
  },
  {
    id: "special-crosswalk",
    type: "daylighting",
    description: "No parking in a marked crosswalk",
    fine: 110,
    details:
      "Parking or stopping in a marked crosswalk is prohibited at all times. Fine is $110. This applies even if no pedestrians are present. Combined with the AB 413 daylighting rule, you must be at least 20 feet from the crosswalk.",
  },
  {
    id: "special-bus-stop",
    type: "daylighting",
    description: "No parking within 15 feet of a bus stop",
    fine: 283,
    details:
      "No stopping, standing, or parking within 15 feet before or after a Muni bus stop. Marked with red curb and bus stop signage. Fine is $283. Vehicles may be towed if blocking bus operations. Applies to all bus stops citywide, even those that appear unused.",
  },
  {
    id: "special-expired-registration",
    type: "oversized-vehicle",
    description: "Vehicles with expired registration will be cited and may be towed after 72 hours",
    fine: 110,
    details:
      "Parking a vehicle with expired registration on a public street is a citable offense ($110). If the vehicle remains for 72+ hours, SFMTA may tow it as an abandoned vehicle. Current California registration tags must be displayed. Temporary operating permits are accepted.",
  },
]

// ============================================================================
// RESIDENTIAL PERMIT PARKING (RPP) ZONES — all 31 active zones
// ============================================================================

const permitZones: PermitZoneEntry[] = [
  { id: "rpp-A", zoneName: "A", neighborhood: "Telegraph Hill / North Waterfront", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-B", zoneName: "B", neighborhood: "Pacific Heights / Presidio Heights", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-C", zoneName: "C", neighborhood: "Russian Hill", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-D", zoneName: "D", neighborhood: "Nob Hill", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-E", zoneName: "E", neighborhood: "Chinatown / Financial District West", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 60, annualCost: 159 },
  { id: "rpp-F", zoneName: "F", neighborhood: "North Beach", days: [0, 1, 2, 3, 4, 5, 6], startTime: "08:00", endTime: "22:00", nonResidentLimit: 60, annualCost: 159 },
  { id: "rpp-G", zoneName: "G", neighborhood: "Anza Vista / Western Addition North", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-H", zoneName: "H", neighborhood: "Western Addition / Alamo Square", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-I", zoneName: "I", neighborhood: "UCSF / Parnassus Heights", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-J", zoneName: "J", neighborhood: "Inner Sunset", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-K", zoneName: "K", neighborhood: "Duboce Triangle / Lower Haight", days: [0, 1, 2, 3, 4, 5, 6], startTime: "08:00", endTime: "22:00", nonResidentLimit: 60, annualCost: 159 },
  { id: "rpp-L", zoneName: "L", neighborhood: "Castro / Eureka Valley", days: [0, 1, 2, 3, 4, 5, 6], startTime: "08:00", endTime: "22:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-M", zoneName: "M", neighborhood: "Marina / Cow Hollow", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-N", zoneName: "N", neighborhood: "Mission (North)", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-O", zoneName: "O", neighborhood: "SOMA West", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-P", zoneName: "P", neighborhood: "Haight-Ashbury / Cole Valley", days: [0, 1, 2, 3, 4, 5, 6], startTime: "08:00", endTime: "22:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-Q", zoneName: "Q", neighborhood: "Inner Richmond", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-R", zoneName: "R", neighborhood: "Potrero Hill / Dogpatch", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-S", zoneName: "S", neighborhood: "Bernal Heights", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-T", zoneName: "T", neighborhood: "Noe Valley", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-U", zoneName: "U", neighborhood: "Mission (South) / Outer Mission", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-V", zoneName: "V", neighborhood: "Hayes Valley / Lower Pacific Heights", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-W", zoneName: "W", neighborhood: "Glen Park", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-X", zoneName: "X", neighborhood: "Japantown / Fillmore", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-Y", zoneName: "Y", neighborhood: "SOMA East / South Beach", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-Z", zoneName: "Z", neighborhood: "Mission Bay", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-AA", zoneName: "AA", neighborhood: "Visitacion Valley", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-BB", zoneName: "BB", neighborhood: "Excelsior / Crocker-Amazon", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-CC", zoneName: "CC", neighborhood: "Bayview / Hunters Point", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-DD", zoneName: "DD", neighborhood: "Oceanview / Ingleside", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
  { id: "rpp-EE", zoneName: "EE", neighborhood: "Portola / University Mound", days: [1, 2, 3, 4, 5], startTime: "08:00", endTime: "18:00", nonResidentLimit: 120, annualCost: 159 },
]

// ============================================================================
// CITY-WIDE RULES — universal parking laws in San Francisco
// ============================================================================

const cityWideRules = {
  /** No vehicle may remain parked on any public street for more than 72 consecutive hours */
  maxParkingHours: 72,
  /** Minimum distance from a fire hydrant (feet) per CVC 22514 */
  hydrantDistance: 15,
  /** AB 413 daylighting: no parking within 20 feet of a crosswalk (effective Jan 2025) */
  crosswalkDistance: 20,
  /** Minimum distance from a bus stop (feet) */
  busStopDistance: 15,
  /** Blocking any driveway is prohibited 24/7 */
  drivewayBlocking: "No blocking any driveway entrance",
  /** Hill parking requirement on grades over 3% */
  hillParking:
    "Must curb wheels on grades > 3%: uphill = wheels away from curb, downhill = wheels toward curb",
  /** Fine for double parking */
  doubleParkingFine: 110,
  /** Fine for parking in a bike lane */
  bikeLaneParkingFine: 110,
  /** Fine for blocking a bus stop */
  busStopFine: 283,
  /** Fine for parking in a disabled space without placard */
  disabledParkingFine: 250,
  /** Street sweeping ticket fine */
  streetSweepingFine: 76,
  /** Standard expired meter fine */
  expiredMeterFine: 76,
  /** Sidewalk parking fine */
  sidewalkParkingFine: 165,
  /** Red zone (fire lane) fine */
  redZoneFine: 110,
  /** Meter enforcement hours citywide default */
  meterHours: "9AM-6PM Mon-Sat (extended in tourist/entertainment areas)",
  /** Payment app accepted at all SFMTA meters */
  meterPayApp: "PayByPhone",
  /** SFMTA customer service */
  sfmtaPhone: "311 or (415) 701-2311",
  /** Tow desk phone number */
  towDeskPhone: "(415) 553-1235",
  /** City tow lot address */
  towLotAddress: "450 7th St, San Francisco, CA 94103",
  /** Average tow + storage cost */
  averageTowCost: "$575+ (tow fee + admin fee + storage)",
  /** Holidays when meters and sweeping are suspended */
  enforcementHolidays: [
    "New Year's Day",
    "Martin Luther King Jr. Day",
    "Presidents' Day",
    "Cesar Chavez Day",
    "Memorial Day",
    "Juneteenth",
    "Independence Day",
    "Labor Day",
    "Indigenous Peoples' Day",
    "Veterans Day",
    "Thanksgiving Day",
    "Day after Thanksgiving",
    "Christmas Day",
  ],
} as const

// ============================================================================
// EXPORT — single comprehensive object
// ============================================================================

export const SF_DATABASE = {
  /** Common sign types found on SF streets with their exact meaning */
  signs,

  /** Night/overnight parking rules by neighborhood */
  nightParking,

  /** Public parking lots and garages with real addresses and rates */
  parkingLots,

  /** Special rules unique to SF that people don't think about */
  specialRules,

  /** Residential permit parking zones (all 31 active RPP zones) */
  permitZones,

  /** City-wide rules that apply everywhere in San Francisco */
  cityWideRules,
} as const
